direct_brokers=["Axis sec","Geojit","Geojith","IDBI sec","SMIFS","Share India" ,"HDFC Sec","IDBI Capital","Mirae Asset","Sharekhan"]
brokers={
        "Motilal": "Motilal Oswal",
        "MOSL":"Motilal Oswal",
        "Emkay": "Emkay Global Financial",
        "ICICI Sec":"ICICI Securities",
        "ICICI Direct":"ICICI Direct",
        "idirect":"ICICI Direct",
        "Axis":"Axis Securities",
        "Prabhudas":"Prabhudas Lilladher",
        "PL Capital":"Prabhudas Lilladher",
        "Edelweiss" : "Edelweiss Securities",
        "Nuvama":"Edelweiss Securities",
        "JM Fin":"JM Financial",
        "Dolat":"Dolat Capital Market",
        "Systematix":"Systematix",
        "Choice": "Choice Equity Broking",
        "Deven Choksey":"Deven Choksey",
        "DR Choksey":"Deven Choksey",
        "DRChoksey"   :"Deven Choksey",
        "IDBI Capital":"IDBI Capital",
        "Keynote":"Keynote Capital",
        "Ashika" : "Ashika Stock broking",
        "InCred": "InCred Equities",
        "Kotak Securi" :"Kotak Securities",
        "Nirmal Bang"  : "Nirmal Bang",
        "Yes Sec"     : "Yes Securities",
        "Geojit"       : "Geojit Financial Services",
        "Mirae"        : "Mirae Asset Sharekhan",
        "Sharekhan"    :"Mirae Asset Sharekhan",
        "Share khan"  : "Mirae Asset Sharekhan",
        "Elara"       :"Elara Capital",
        "Anand Rathi": "Anand Rathi",
        "Philip Capital": "Philip Capital",
        "Ventura"    : "Ventura Securities",
        "SBI sec"    : "SBI Securities",
        "SMIFS"      : "SMIFS",
        "LKP"        : "LKP Research",
        "Arihant"    :"Arihant Capital",
        "HEM Sec"    :"HEM Securities",
        "MOFSL"      :"Motilal Oswal",
        "HDFC Secur" : "HDFC Securities",
        "Share India":"Share India",
        "Centrum"    :"Centrum Broking",
        "SMC Global" :"SMC Global",
        "B&K"        :"B&K Securities",
        "Trinetra Asset":" Trinetra Asset Managers",
        "Equirus":"Equirus Securities",
        "Mastertrust" : "MasterTrust",
        "Scoop":"Scoop Investment",
        "Investec" :"Investec",
        "DAM capital":"DAM Capital",
        "Networth Capital":"Networth Capital",
        "Khambatta":"Khambatta Securities",
        "Antique":"Antique Broking",
        "CLSA"   :"CLSA",
        "Ambit"  :"Ambit",
        "Goldman":"Goldman Sachs",
        "Jeffries":"Jeffries",
        "Nomura"  :"Nomura",
        "UBS"     :"UBS",
        "Morgan"  :"JP Morgan",
        "MNCL"    :"Monarch Networth Capital Linited",
        "DSP"     :"DSP",
        "Sunidhi":"Sunidhi",
        "BP Equities":" BP Equities",
        "Bernstein":" Bernstein",
        "NDA Securi":"NDA Securities",
        "FRONTWAVERESEARCH":"FRONTWAVERESEARCH"
        }
